# Generated by Django 4.2.3 on 2023-10-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0002_managerclerk'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='enter_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
