# Generated by Django 4.2.3 on 2023-10-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0005_attempts_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
