# Generated by Django 4.2.3 on 2023-10-03 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_management.form'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.form'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
    ]
