# Generated by Django 4.2.3 on 2023-10-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_userproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='field_required',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='form',
        ),
        migrations.AddField(
            model_name='company',
            name='comapany_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_reg_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
