# Generated by Django 4.2.3 on 2023-10-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_remove_formfield_field_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comapany_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_reg_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=100),
        ),
    ]
